# Netlify configuration for Farmer Rice frontend

[build]
  command = "npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_VERSION = "9.0.0"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

# Production context
[context.production.environment]
  REACT_APP_API_URL = "https://farmerice-echi.onrender.com/api"
  NODE_ENV = "production"

# Branch deploy context
[context.staging.environment]
  REACT_APP_API_URL = "https://farmerice-echi.onrender.com/api"
  NODE_ENV = "production"

# Development branch context
[context.development.environment]
  REACT_APP_API_URL = "https://farmerice-echi.onrender.com/api"
  NODE_ENV = "development"

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://farmerice-echi.onrender.com; img-src 'self' data: https://res.cloudinary.com https://farmerice-echi.onrender.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://farmerice-echi.onrender.com https://farmerice-echi.onrender.com/api;"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API requests
[[redirects]]
  from = "/api/*"
  to = "https://farmerice-echi.onrender.com/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization" 