services:
  - type: web
    name: farmerice-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5015
    healthCheckPath: /health 